### ISSUE TITLE
Add an opinionated eslint config

### ISSUE THREAD

**Issue by Larsklopstra** [laravel-frontend-presets/inertiajs#19]
This would be useful for auto formatting and increases the developer experience instead of installing your own, you could always edit or remove the config if you're not into linting.

**Comment by michaeldyrynda** [comment]
I don't have any opinions when it comes to Javascript, however, I'd be happy to accept a PR that just mirrors what is in the [PingCRM repo](https://github.com/inertiajs/pingcrm/blob/master/.eslintrc.js).
